### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by nikezono** [the-weekly-paper/the-weekly-paper.github.io#2]
バズってくれとは夢にも思いませんが,
論文タイトルで検索した時に検索結果に出る程度はインデックスされてくれると,
有意義な議論に繋がるので, 何とかしたいですね.
今の所 `jekyll new` しただけなのでやり方も全くわかりませんが.

**Comment by ytanaka-** [comment]
はてブが付くかTwiiterで共有されれば流入はありそう。OGPタグとかつけられるとよさそう

**Comment by nikezono** [comment]
なるほど．

とりあえずgoogleにインデックスされる方法がわからない．．．

**Comment by ytanaka-** [comment]
とりあえずはてぶすればクロール対象に含まれるんじゃないかしら

**Comment by nikezono** [comment]
https://www.google.co.jp/search?q=site:the-weekly-paper.github.io
なんかぼちぼちできてる感があるのでよさそう

**Comment by ytanaka-** [comment]
お、昨日まではトップだけだったんだけどな

**Comment by nikezono** [comment]
https://www.google.co.jp/search?q=site%3Athe-weekly-paper.github.io
霊圧が消えた

**Comment by nikezono** [comment]
なんかクロールされてる
